# Generated by Django 2.0.8 on 2018-08-24 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='refer',
            name='useYn',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='refer',
            name='after',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='before', to='todos.Todo'),
        ),
        migrations.AlterField(
            model_name='refer',
            name='before',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='after', to='todos.Todo'),
        ),
    ]
