# Generated by Django 2.0.8 on 2018-08-25 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_auto_20180825_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('doing', 'Doing'), ('done', 'Done')], default='doing', max_length=50),
        ),
    ]
