# Generated by Django 2.0.8 on 2018-08-25 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_auto_20180825_0922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refer',
            name='useYn',
        ),
    ]
